name: Deploy

on:
  workflow_run:
    workflows: ["Build"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: SSH into EC2 and deploy JAR
        run: |
          ssh ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            echo "Downloading JAR from S3..."
            aws s3 cp s3://${{ secrets.S3_BUCKET }}/deploy/demo-0.0.1-SNAPSHOT.jar demo-0.0.1-SNAPSHOT.jar --region ${{ secrets.AWS_REGION }}

            echo "Killing any existing Java app..."
            pkill -f 'java -jar' || true

            echo "Starting new Java app..."
            nohup java -jar demo-0.0.1-SNAPSHOT.jar > app.log 2>&1 &
          EOF
